### ISSUE TITLE
Unable to connect to demo. SSL certificate has expired."ERR_CERT_COMMON_NAME_INVALID"

### ISSUE THREAD

**Issue by haruharu-1105** [NVlabs/Sana#12]
Hello.

## Problem
From around 9am today
Unable to connect to demo. URL:https://sana-gen.mit.edu/
## Cause (probably)
It looks like the SSL certificate was updated to an expired one for some reason.
reason 1, The common name of the SSL certificate "rlecs3.mit.edu" and the domain "sana-gen.mit.edu" do not match.
Error message "net::ERR_CERT_COMMON_NAME_INVALID." displayed in Chrome

reason 2, This is because the demo domain's **SSL certificate has expired**. 
Error message "net::ERR_CERT_DATE_INVALID." displayed in Chrome

![image](https://github.com/user-attachments/assets/5da52b62-06bc-4547-af85-2063193cfb8c)
### Execution environment
  - Windows 10 using Chrome and Edge
  - smartphone using Android Chrome
  - I checked with SSLChecker.
    - https://www.sslshopper.com/ssl-checker.html#hostname=sana-gen.mit.edu

### As an alternative, I'm using this demo.
https://24b5795674fcf4e2b0.gradio.live/

Thank you for reading this far.

**Comment by haruharu-1105** [comment]
According to commit log 62234230ad11d0d1d97eafe976410e7efdb67123 , the demo link seems to have been changed to https://nv-sana.mit.edu
A demo is now available at the above address. thank you.

The problem has been resolved, but I will leave this issue open for a week.
This is information for people who came to see the issue due to a browser error. Then close the issue.

**Comment by Xenodermus** [comment]
Looks good now. Thanks 😊 
-------- Original message --------From: haruharu-1105 ***@***.***> Date: 02/11/2024  00:26  (GMT+00:00) To: NVlabs/Sana ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [NVlabs/Sana] Unable to connect to demo. SSL certificate has expired."ERR_CERT_COMMON_NAME_INVALID" (Issue #12) 
According to commit log 6223423 , the demo link seems to have been changed to https://nv-sana.mit.edu
A demo is now available at the above address. thank you.
The problem has been resolved, but I will leave this issue open for a week.
This is information for people who came to see the issue due to a browser error. Then close the issue.

**Comment by Xenodermus** [comment]
Not sure what is going on now, but I can only run the example prompts. None
of my inputted prompts work and always get an "ERROR" message

**Comment by haruharu-1105** [comment]
https://nv-sana.mit.edu/
![image](https://github.com/user-attachments/assets/00cb2e41-6b96-469b-ae9a-f6b858ecf2ee)
I just generated it and it was generated successfully.
One possibility is that something has temporarily interrupted the demo.
If the problem continues to occur frequently, it may be better to raise a new issue instead of this SSL issue.
