### ISSUE TITLE
"All the checkpoints will be downloaded automatically."

### ISSUE THREAD

**Issue by matbee-eth** [NVlabs/Sana#79]
They dont download automatically in comfyui.

**Comment by lawrence-cj** [comment]
How did you use it?

**Comment by ceramicv** [comment]
I grabbed their example workflows and looked at the model names, then googled the name and downloaded them from Huggingface. But on generation all I get is a black image so I think I may have a wrong model  or version downloaded

**Comment by matbee-eth** [comment]
Yeah I had to manually download the models, the workflows dont include a downloader node

**Comment by lawrence-cj** [comment]
Workflow screenshot or json file,pls?

**Comment by adamreading** [comment]
Can anyone help with the model path expected for Gemma in Comfyui please - it can't autodownload because the model is gated - I have downloaded the files locally but need to upload to the expected structure- as I still get the 401 error when I hit queue whatever I call the directory (currently its in models/LLM/google/gemma-2-2b-it because that's what the workflow seems to be looking for

**Comment by adamreading** [comment]
> Besides, to be more clearly. This is our ComfyUI node: https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels

Thanks, I wasn’t impressed with the Sana quality so didn’t peruse the workflow in the end thank you.
